### ISSUE TITLE
I changed Research badge to be Ideation badge

### ISSUE THREAD

**Issue by watkinspd** [watkinspd/docs#1]
I think Ideation may be a better label for stage we were calling Research. Also, blue is a better color because it can mean "blue sky" which is more aligned to the intent of the stage. Thoughts?

If people like this idea I can submit a pull request to BCDevExchange for their consideration.

It's a way to simulate collaborating in the open on ideas just like this.

**Comment by AlexWhiteIncorporated** [comment]
I like the blue, and it seems like "Ideation" is a real word, so could work. Other suggested ideas were "Experimental" and "Exploration" (from Andy at MoE). All would work for me. 

FYI - The changes you made to the non-badge labels (Icons, Letters, small banners, large banners) for the Research items broke the links (they were referencing .png files in the docs/images folder). These may get scrapped anyways (they were an early stage idea), though I think we might want something that works for physical documents, which also contains the description / definition of the state (like, this document is Research / Ideation, and that means xyz). That's the requirement the large banner was trying to meet.

**Comment by watkinspd** [comment]
I changed it again. This time to "Inspiration", closing this issue, opening a new one.
